export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";

export const PAGE_LOADING = "PAGE_LOADING";

export const NAME_SEARCH = "NAME_SEARCH";

export const GET_API_GENRES = "GET_API_GENRES";

export const CREATE_GAME = "CREATE_GAME";

export const ORDER = "ORDER";

export const FILTER_ADDED_BY = "FILTER_ADDED_BY";

export const FILTER_GENRES = "FILTER_GENRES";

export const SHOWING_SEARCH = "SHOWING_SEARCH";

export const CLEAN_VIDEOGAMES = "CLEAN_VIDEOGAMES";